### ISSUE TITLE
Error in t.py

### ISSUE THREAD

**Issue by ghost** [glangsto/analyze#1]
As I was trying your "C -B -C 4000 data/*" example for the README.md I got the following error: 

Plotting Intensity vs Velocity, Average time: 4000 (seconds)
Found   5 Hot load observations
Min, Max Galactic Latitude:    -2.6,   43.2
Min, Max Elevation:           -40.0,   70.0
Traceback (most recent call last):
  File "./t.py", line 461, in <module>
    hotcold.flagCenter( cv, nData)
NameError: name 'cv' is not defined

and looking into t.py I found that 'cv' is indeed not defined within the if statement or before entering it. The example works without the 'C' option though.

Thanks for all your work.

**Comment by glangsto** [comment]
Hello GiGa-Astro,

I just was working with this today.   I may
have added an error.

When did you “git-pull” the code?   This issue
may have gotten fixed later.

Based on your message, you are requesting flagging of the cennter
channel.  If that is not requested, does the code work?

Best regards

Glen

Glen I Langston, Ph. D.
Galactic Astronomy Program Director
National Science Foundation
304-456-3032

**Comment by glangsto** [comment]
Hello Giga-astro,

You’re absolutely correct.  I found the
problem and pushed a solution.

Please do a "git pull" in your "analyze” directory.

I’ve tested it after the fix.   But I thought I’d already
checked this.   

Thanks for your feedback!

Best regards

Glen

Glen I Langston, Ph. D.
Galactic Astronomy Program Director
National Science Foundation
304-456-3032
